### ISSUE TITLE
Label compatible modules in the module overview

### ISSUE THREAD

**Issue by RobinTheHood** [RobinTheHood/ModifiedModuleLoaderClient#1]
A feature to label modules in the module overview:
- compatible (with the installed shop version)
- incompatible (with the installed shop version)

This could increase the interest of modules.

There is already a method you can use to check for compatible with the installed shop version. You can use it in `/src/Templates/ModuleListing.tmpl.php`.

Here is a code hint:

```php
...
if ($module->isCompatible()) {
    // show label
}
...

**Comment by jayhybrid** [comment]
I'll have a look into this, can't promise anything though.
