### ISSUE TITLE
Problem mit dem Link "zurück zum Shopadmin"

### ISSUE THREAD

**Issue by hpzeller** [RobinTheHood/ModifiedModuleLoaderClient#66]
Hallo
Ich habe in meiner MMLC Installation ein Problem mit dem Link "zurück zum Shopadmin", dieser sieht beim mir so aus `https://domain.tld/admin_XXXXXXXXXX/start.php`, er sollte aber, da der Shop in einem Verzeichnis installiert ist, so aussehen `https://domain.tld/verzeichnis/admin_XXXXXXXXXX/start.php`.

Gruss
Hanspeter

**Comment by RobinTheHood** [comment]
Hallo Hanspeter, vielen Dank für dein Issue. Hab dir noch mal im modified Forum geantwortet. Da hab ich auch deinen Code Vorschlag gesehen. Wünsche dir einen schönen Abend. 😊

**Comment by RobinTheHood** [comment]
fixed with 7c5401bb8f7b554fa8fd461da52e26a93e074adf
