### ISSUE TITLE
Modul description is not rendered as Markdown

### ISSUE THREAD

**Issue by grandeljay** [RobinTheHood/ModifiedModuleLoaderClient#74]
The modul description is not rendered as markdown.

Furthermore, it's very difficult to squeeze it all into a single line into the `modulinfo.json`. It would be great to have a `/docs/description.md`

https://discord.com/channels/727190419158597683/727191639537221652/1072129464831586374

**Comment by RobinTheHood** [comment]
I like the idea. 😊
