### ISSUE TITLE
Add support for `sourceMmlcDir`

### ISSUE THREAD

**Issue by grandeljay** [RobinTheHood/ModifiedModuleLoaderClient#76]
Add source directory for the MMLC:
```json
{
    "sourceDir": "src",
    "sourceDirMmlc": "src-mmlc",
}
```
Everything in within the `sourceDirMmlc` directory will be copied to `/vendor-no-composer/vendor-name/project-name`.

**Comment by RobinTheHood** [comment]
I like the idea! 👍
